corpus_path: ./corpus
AZURE_OPENAI_API_KEY: os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_CHAT_DEPLOYMENT_NAME: gpt-4o-mini
AZURE_EMBEDDING_OPENAI_CHAT_DEPLOYMENT_NAME: text-embedding-3-large
top_k: 2