import streamlit as st


AZURE_OPENAI_API_KEY = st.secrets["AZURE_OPENAI_API_KEY"]
AZURE_OPENAI_ENDPOINT = st.secrets["AZURE_OPENAI_ENDPOINT"]
EMBEDDING_DEPLOYMENT = st.secrets["EMBEDDING_DEPLOYMENT"]
CHAT_DEPLOYMENT = st.secrets["CHAT_DEPLOYMENT"]
CORPUS_PATH = st.secrets["CORPUS_PATH"]
TOP_K = st.secrets["TOP_K"]
